version: 2
build:
  os: ubuntu-lts-latest
  tools:
    rust: latest
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv run --frozen --no-cache --python 3.12 mkdocs build -d $READTHEDOCS_OUTPUT/html
